CREATE TABLE IF NOT EXISTS ordenes_compra (
    id_orden_compra INT UNSIGNED NOT NULL AUTO_INCREMENT,
    id_presupuesto INT UNSIGNED NOT NULL,
    id_previsita INT UNSIGNED NOT NULL,
    cliente_snapshot TEXT NULL,
    numero_oc VARCHAR(100) DEFAULT NULL,
    fecha_emision DATE DEFAULT NULL,
    proveedor VARCHAR(150) DEFAULT NULL,
    moneda VARCHAR(10) NOT NULL DEFAULT 'ARS',
    monto_neto DECIMAL(15,2) DEFAULT NULL,
    iva_incluido TINYINT(1) NOT NULL DEFAULT 0,
    total DECIMAL(15,2) DEFAULT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'cargada',
    condicion_pago TEXT NULL,
    requiere_anticipo TINYINT(1) NOT NULL DEFAULT 0,
    anticipo_tipo VARCHAR(20) DEFAULT NULL,
    anticipo_valor DECIMAL(15,2) DEFAULT NULL,
    condicion_saldo TEXT NULL,
    observaciones_comerciales TEXT NULL,
    direccion_entrega TEXT NULL,
    sucursal_planta_sede VARCHAR(255) DEFAULT NULL,
    fecha_entrega_prevista DATE DEFAULT NULL,
    contacto_sitio VARCHAR(255) DEFAULT NULL,
    contacto_sitio_email VARCHAR(255) DEFAULT NULL,
    contacto_sitio_telefono VARCHAR(100) DEFAULT NULL,
    email_facturacion VARCHAR(255) DEFAULT NULL,
    area_facturacion VARCHAR(255) DEFAULT NULL,
    factura_menciona_oc TINYINT(1) NOT NULL DEFAULT 1,
    factura_menciona_destino TINYINT(1) NOT NULL DEFAULT 0,
    instrucciones_facturacion TEXT NULL,
    requiere_documentacion_seguridad TINYINT(1) NOT NULL DEFAULT 0,
    contactos_ingreso TEXT NULL,
    estado_documentacion_seguridad VARCHAR(50) DEFAULT NULL,
    observaciones_seguridad TEXT NULL,
    pdf_nombre_archivo VARCHAR(255) DEFAULT NULL,
    pdf_ruta_archivo TEXT NULL,
    pdf_mime_type VARCHAR(100) DEFAULT NULL,
    pdf_tamano_bytes BIGINT UNSIGNED DEFAULT NULL,
    id_usuario_alta INT UNSIGNED DEFAULT NULL,
    id_usuario_modificacion INT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id_orden_compra),
    KEY idx_oc_presupuesto (id_presupuesto),
    KEY idx_oc_previsita (id_previsita),
    KEY idx_oc_estado (estado),
    KEY idx_oc_numero (numero_oc),
    KEY idx_oc_fecha_emision (fecha_emision),
    KEY idx_oc_created_at (created_at),
    KEY idx_oc_presupuesto_estado (id_presupuesto, estado)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
