CREATE TABLE IF NOT EXISTS presupuesto_documentos_emitidos_envios (
    id_envio INT UNSIGNED NOT NULL AUTO_INCREMENT,
    id_documento_emitido INT UNSIGNED NOT NULL,
    id_presupuesto INT UNSIGNED NOT NULL,
    id_previsita INT UNSIGNED NOT NULL,
    id_usuario INT UNSIGNED NOT NULL,
    modo_envio ENUM('simulacion','smtp') NOT NULL,
    estado_envio ENUM('simulado','enviado','fallido') NOT NULL,
    para_email TEXT NOT NULL,
    cc TEXT DEFAULT NULL,
    cco TEXT DEFAULT NULL,
    asunto VARCHAR(255) NOT NULL,
    cuerpo MEDIUMTEXT DEFAULT NULL,
    remitente_email VARCHAR(255) DEFAULT NULL,
    remitente_nombre VARCHAR(150) DEFAULT NULL,
    mensaje_error TEXT DEFAULT NULL,
    respuesta_transporte TEXT DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_envio),
    KEY idx_pdee_documento (id_documento_emitido),
    KEY idx_pdee_presupuesto (id_presupuesto),
    KEY idx_pdee_previsita (id_previsita),
    KEY idx_pdee_estado_fecha (estado_envio, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
